<?php
// src/Blogger/BlogBundle/Entity/Repository/BlogRepository.php

namespace Blogger\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
    public function
    getLatestBlogs(
        $limit = null)
    {
        $queryBuilder = $this->createQueryBuilder('b')
                             ->select('b')
                             ->addOrderBy('b.created', 'DESC');

        if (!is_null($limit))
        {
            $queryBuilder->setMaxResults($limit);
        }

        return $queryBuilder->getQuery()->getResult();
    }
}
